### ISSUE TITLE
Getting "Cannot find module" but everything is installed and precompiler file does exist

### ISSUE THREAD

**Issue by ahimanikya** [bicouy0/sbt-hbs#1]
[error] module.js:340
[error]     throw err;
[error]           ^
[error] Error: Cannot find module 'handlebars/lib/precompiler'
[error]     at Function.Module._resolveFilename (module.js:338:15)
[error]     at Function.Module._load (module.js:280:25)
[error]     at Module.require (module.js:364:17)
[error]     at require (module.js:380:17)

**Comment by gbicou** [comment]
Did you installed handlebarsjs globally with npm or with package.json file ?

**Comment by ahimanikya** [comment]
Yes, I did install with -g option in my MacPro

sudo npm install handlebars -g

**Comment by gbicou** [comment]
Try switching your engine by adding `JsEngineKeys.engineType := JsEngineKeys.EngineType.Node` to your `build.sbt` or any other engine.

**Comment by ahimanikya** [comment]
I already have that, I am using other node based sbt modules

**Comment by gbicou** [comment]
Next release will use handlebars from org.webjars instead

**Comment by gbicou** [comment]
Can you try v1.0.4 ?

**Comment by ahimanikya** [comment]
Now it says:

[error] module.js:340
[error]     throw err;
[error]           ^
[error] Error: Cannot find module 'handlebars'
[error]     at Function.Module._resolveFilename (module.js:338:15)
[error]     at Function.Module._load (module.js:280:25)
[error]     at Module.require (module.js:364:17)
[error]     at require (module.js:380:17)

**Comment by ahimanikya** [comment]
I was comparing with sbt-less, everything looks similar except the following lines, which is there in sbt-hbs and not in sbt-less (for me sbt-less works fine)

 nodeModuleGenerators in Plugin <+= npmNodeModules in Assets,
 nodeModuleDirectories in Plugin += baseDirectory.value / "node_modules"

**Comment by gbicou** [comment]
sbt-less depends on `"org.webjars" % "less-node"` which has a `package.json`.

`"org.webjars" % "handlebars"` does not that's why sbt-hbs is based on sbt-emberjs code, maybe sbt-emberjs does not work for you either.

**Comment by gbicou** [comment]
Did you try adding a `package.json` in your play application instead of relying on `npm install -g` ?

**Comment by ahimanikya** [comment]
I don't have package.json, I can try that route

**Comment by gbicou** [comment]
Can i ask you to do a checkout of `git@github.com:bicouy0/sbt-hbs.git`, and in the directory sbt-hbs/ launch the command `sbt scripted` ? Thanks in advance !

**Comment by ahimanikya** [comment]
[info] Handlebars compiling on 1 source(s)
i am getting this message

[info] [error] /private/var/folders/gg/48g3p5313mbd_kh96p1d3ssr0000gn/T/sbt_fa4dd4d2/partial/src/main/assets/_test.hbs:0: Object #<HandlebarsEnvironment> has no method 'cli'
[info] [error] unknown line content
[info] [error] ^
[info] [error] one error found
[info] [error](web-assets:hbs) com.typesafe.sbt.web.CompileProblemsException
[info] [error] Total time: 12 s, completed 5 Feb, 2015 9:59:13 PM
[error] x sbt-hbs / partial
[error]    {line 1}  Command failed: web-stage failed

**Comment by ahimanikya** [comment]
I recently tried this in linux - same error...

Love to see how I can resolve this...

**Comment by ahimanikya** [comment]
I was able to make it work using package.json
