### ISSUE TITLE
Concatenate all compiled templates in a single file

### ISSUE THREAD

**Issue by davidcampos** [bicouy0/sbt-hbs#3]
Is it possible to concatenate all compiled handlebars in a single file?

I have tried using sbt-concat with:
`Concat.groups := Seq(
  "templates.js" -> group((WebKeys.webTarget in Assets).value / "hbs" / "main" / "templates" ** "*.js")
)`

However, it is not able to generate the concatenated file, providing the following warning messages:
`[warn] Unable to process about.js. Not found.
[warn] Unable to process account.js. Not found.
[warn] Unable to process demo.js. Not found.
...`

Could you please integrate this feature as a setting or help me generating the concatenated file?
Thanks for your help.

**Comment by rwijngaa** [comment]
Hi, i got the exact same issue. Did you ever solve it?
